var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0e37d43f._.js")
R.c("server/chunks/ssr/projects_astralis-nextjs_77cb1e61._.js")
R.c("server/chunks/ssr/0780a_next_dist_esm_build_templates_app-page_2c996912.js")
R.c("server/chunks/ssr/[root-of-the-server]__81c251a0._.js")
R.c("server/chunks/ssr/0780a_c038eebf._.js")
R.c("server/chunks/ssr/0780a_next_dist_7e66dcf9._.js")
R.c("server/chunks/ssr/projects_astralis-nextjs_src_app_a895177a._.js")
R.c("server/chunks/ssr/projects_astralis-nextjs_src_b4e7598e._.js")
R.c("server/chunks/ssr/0780a_next_dist_client_components_5c3698fd._.js")
R.c("server/chunks/ssr/0780a_next_dist_client_components_builtin_forbidden_c24c321e.js")
R.c("server/chunks/ssr/9e3a1_astralis-nextjs__next-internal_server_app__not-found_page_actions_abc0f4e9.js")
R.m(880694)
module.exports=R.m(880694).exports
